### ISSUE TITLE
labels.pkl file for the hybrid model i.e. with 1365 categories

### ISSUE THREAD

**Issue by SumanthReddyKaliki** [CSAILVision/places365#15]
Hi, can you share the **labels.pkl** file for the for the **hybrid model** with 1365 categories. I want to build a **docker container** with resnet hybrid model in that. but I didn't find any labels.pkl file for it. It will be very helpful if you can share the file.

**Comment by metalbubble** [comment]
The original label should be here https://github.com/CSAILVision/places365/blob/master/categories_hybrid1365.txt
