### ISSUE TITLE
Error in running docker build command

### ISSUE THREAD

**Issue by uahsan3** [CSAILVision/places365#16]
When I run 

`docker build -t places365_container .`

I get this error:

```
---> Running in db1ece13a39a
--2017-01-31 18:04:36--  http://places2.csail.mit.edu/models_places365/alexnet_places365.caffemodel
Resolving places2.csail.mit.edu (places2.csail.mit.edu)... failed: Name or service not known.
wget: unable to resolve host address 'places2.csail.mit.edu'
INFO[0045] The command [/bin/sh -c wget http://places2.csail.mit.edu/models_places365/alexnet_places365.caffemodel] returned a non-zero code: 4 

```

Any advice? 

Thanks!

**Comment by SumanthReddyKaliki** [comment]
Try to do 
`sudo docker build -t places365_container .`

That worked for me.

**Comment by vineetasingh** [comment]
I am faced with the same issue. . I tried @SumanthReddyKaliki 's solution and ran `sudo docker build -t places365_container .`   It is giving me an eror 

> Running in 19bd61ff6263
--2018-07-07 16:57:19--  http://places2.csail.mit.edu/models_places365/alexnet_places365.caffemodel
Resolving places2.csail.mit.edu (places2.csail.mit.edu)... failed: Name or service not known.
wget: unable to resolve host address 'places2.csail.mit.edu'
The command '/bin/sh -c wget http://places2.csail.mit.edu/models_places365/alexnet_places365.caffemodel' returned a non-zero code: 4
