### ISSUE TITLE
Torch version of Caffe models

### ISSUE THREAD

**Issue by arefiyan** [CSAILVision/places365#21]
Could you provide the Torch version of following models, please? I couldn't load and convert them. Thanks

AlexNet-places365
GoogLeNet-places365
VGG16-places365
VGG16-hybrid1365
ResNet152-hybrid1365

**Comment by metalbubble** [comment]
torch 7. 
require 'loadcaffe'
model = loadcaffe.load('deploy_alexnet_places365.prototxt', 'alexnet_places365.caffemodel', 'cudnn')
