### ISSUE TITLE
Image preprocessing

### ISSUE THREAD

**Issue by bkj** [CSAILVision/places365#26]
Can someone familiar with how the models were trained verify that the preprocessing in `run_placesCNN_basic.py` and `run_placesCNN_unified.py` are both correct?

In `run_placesCNN_basic.py` it's:

```
centre_crop = trn.Compose([
        trn.Scale(256),
        trn.CenterCrop(224),
        trn.ToTensor(),
        trn.Normalize([0.485, 0.456, 0.406], [0.229, 0.224, 0.225])
])
````

That is, rescaling the smaller edge of the image to 256 and then taking the center 224 pix?  

In `run_placesCNN_unified.py`, it's:

```
    tf = trn.Compose([
        trn.Scale((224,224)),
        trn.ToTensor(),
        trn.Normalize([0.485, 0.456, 0.406], [0.229, 0.224, 0.225])
    ])
```

That is, squashing the image to 224x224.  Presumably the appropriate preprocessing should be the one that's closes to what was used for training.

Thanks

**Comment by metalbubble** [comment]
both of the preprocessing are fine. I used the second one because it could generate the Class Activation Mapping more easily.

**Comment by bkj** [comment]
Do you know how the network was trained? I wouldn't expect performance on
natural and squashed images to be the same, unless the model was trained on
a combination of both kinds of images.
