### ISSUE TITLE
whole_wideresnet18_places365 in Caffe

### ISSUE THREAD

**Issue by paffell** [CSAILVision/places365#28]
Hi guys,

this is an excellent work. I really like to unified version of prediction multiple attributes. Do you also have the whole_wideresnet18_places365 model used in the unified version in Caffe? Or can you give me a hint how to convert it? Can I also use a different network in the unified prediction?

**Comment by zccoder** [comment]
i also want to get the code for training process.The open source commited here is just for testing.

**Comment by metalbubble** [comment]
https://github.com/CSAILVision/places365/blob/master/train_placesCNN.py

**Comment by paffell** [comment]
Thank you for the upload. This gave a response to zccoder, but mine was completely different. I don't really know, why zccoder put his question in this Issue.

**Comment by metalbubble** [comment]
there is no such unified caffe model in places365. but there is one in places205-CNN. At http://places.csail.mit.edu/, you could download the scene attribute predictor, indoor outdoor labels, and Places205-AlexNet, then glue them together.

**Comment by paffell** [comment]
Thank you, I will try it
