### ISSUE TITLE
issue with black&white images

### ISSUE THREAD

**Issue by xlxlcyRuSReXxlxl** [CSAILVision/places365#29]
Hi all! I am dealing with a very annoying issue and as I am new at Python I don't know how to go thought. 
Shortly I am running places365 over many images, and it looks that it can't handle with black and white images, since I got the following error:
RuntimeError: Need input of dimension 4 and input.size[1] == 3 but got input to be of shape: [1 x 1 x 224 x 224] at /pytorch/torch/lib/THNN/generic/SpatialConvolutionMM.c:47
As I would not want to delete all the black and white images, could someone suggest me few lines of code that would solve the problem?
Thanks!

**Comment by xuzhentao** [comment]
I meet the same problem. Did you solve it?

**Comment by metalbubble** [comment]
you just add an if check, if it is black and white, you duplicate channel three times for RGB
