### ISSUE TITLE
Which channel order: RGB or BGR

### ISSUE THREAD

**Issue by GrumpyZhou** [CSAILVision/places365#30]
Hi,  
I want to use your models as pre-trained weight for other tasks. However,  I am not sure how you processed your input images, as I saw you have : 

1. ResNet152-places365 fine-tuned from ResNet152-ImageNet
2. ResNet152-places365 trained from scratch using Torch

As the author of [ResNet152-ImageNet](https://github.com/KaimingHe/deep-residual-networks/blob/master/prototxt/ResNet-152-deploy.prototxt), mentioned that he used BGR, which is expected if using caffe... So i guess the model in 1, should also use BGR?  While the model in 2 is not clear to me, as it was trained from scratch and used Torch...  

It would be nice if you can tell me it directly.  Thanks!

**Comment by metalbubble** [comment]
Resnet trained from scratch using RGB order.
