### ISSUE TITLE
How to use deep scene features for new scene classification training?

### ISSUE THREAD

**Issue by ZixuanLiang** [CSAILVision/places365#31]
If we want to test the performance of the deep features of Places365-CNNs, how to set up new training for new dataset such as Scene15?

**Comment by ZixuanLiang** [comment]
I rarely use Caffe, please correct me if I am wrong. For a fine-tune task of smaller dataset, in .prototxt file of pretrained model, we change the names of top layers, and set to zero the "lr_mult" of other layers. In train_placesCNN.py, what do we pass to the --pretrained argument?

**Comment by metalbubble** [comment]
google the tutorial for fine-tuning caffemodel.
