### ISSUE TITLE
error when untar the pytorch model downloaded from DenseNet161.

### ISSUE THREAD

**Issue by frankhyj** [CSAILVision/places365#38]
Excuse me,when i download tar from website, the downloaded file can not be untar. How can i fix this problem? Thanks!

The models are downloaded from websites below.

PyTorch Places365 models: AlexNet, ResNet18, ResNet50, DenseNet161. The models are trained in Python2.7+PyTorch 0.2, when the models are being loaded in python3, you might encounter UnicodeDecodeError, see this issue. Run basic code to get the scene prediction from PlacesCNN:

**Comment by hailsham** [comment]
I also have the same problem, the files can not be untar.

**Comment by metalbubble** [comment]
If you take some minimum effort to look at the demo script (https://github.com/CSAILVision/places365/blob/master/run_placesCNN_basic.py) you won't ask this kind of question...

**Comment by hailsham** [comment]
thanks~
