### ISSUE TITLE
"SCENE ATTRIBUTES" always be same when I try to input more than one pictures with model loaded once

### ISSUE THREAD

**Issue by qingmm** [CSAILVision/places365#52]
I modify the code in run_placesCNN_unified.py to input more than one pictures and just need to load the model once, I write a function which input is picture_path, and output is the results.But is seems that **SCENE ATTRIBUTES** always the same, cause the `features_blobs` is used in `load_model()`, so it doesn't modify when the picture is varying.Does any body else know how to fix this and don't need to load the model every time?

**Comment by qingmm** [comment]
I found that if load modal just once, and every time I input an image the length of features_blobs add 2, but **SCENE ATTRIBUTES** only get features_blobs[1] as below: `responses_attribute = W_attribute.dot(features_blobs[1])`, so just need to del features_blobs[:2] after every function call and before return the results.

**Comment by metalbubble** [comment]
you need to clean up features_blobs for each image.
