### ISSUE TITLE
Inquiry  about 'wideresnet18' model used in  'run_placesCNN_unified.py' 

### ISSUE THREAD

**Issue by HaJinGwan** [CSAILVision/places365#54]
Hello,

For indoor scene classification, I've run 'run_placeCNN_unified.py' code and used 'wideresnet18' model you attached. 

However, I do not know the difference between 'wideresnet18_places365' and 'resnet18_places365' except for maxpooling layer before convolution layer. So, I do not know if it is really wide residual model.

I want to know why you have used 'wideresnet18' model in 'run_placesCNN_unified.py' and named 'wideresnet'.

I would be grateful if you answer my question.
Thanks.

**Comment by fawazsammani** [comment]
Hi. Where did you find the wideresnet model? I have searched in the readme file but couldn't find it. I only found the AlexNet,ResNet18, ResNet50 and DenseNet161.
May you please tell me where you found it?

**Comment by metalbubble** [comment]
wideresent removed the maxpool so the resulting last conv feature map size is large, in that case the heatmap generated will have higher resolution.
