### ISSUE TITLE
Where is the 'W_sceneattribute_wideresnet18.npy' file?

### ISSUE THREAD

**Issue by juliechoong** [CSAILVision/places365#83]
I'm having this error and I can't seem to find the file for it.

FileNotFoundError: [Errno 2] No such file or directory: 'W_sceneattribute_wideresnet18.npy'

**Comment by maryamag85** [comment]
this file is in the repo,

 whole_wideresnet18_places365.pth.tar is missing file!

**Comment by Tia-Cheung** [comment]
> I'm having this error and I can't seem to find the file for it.
> 
> FileNotFoundError: [Errno 2] No such file or directory: 'W_sceneattribute_wideresnet18.npy'

You can download it by link :

> http://places2.csail.mit.edu/models_places365/W_sceneattribute_wideresnet18.npy
