### ISSUE TITLE
The domain http://places2.csail.mit.edu is down

### ISSUE THREAD

**Issue by raj-magesh** [CSAILVision/places365#88]
http://places2.csail.mit.edu/models_places365/alexnet_places365.pth.tar no longer loads

**Comment by lin65505578** [comment]
信已收到，谢谢！我会尽快回复。                林焕

**Comment by raj-magesh** [comment]
Actually, the entire domain http://places2.csail.mit.edu seems to be down.

**Comment by lutharsanen** [comment]
seems to work again

**Comment by raj-magesh** [comment]
Yes, it's working now, thanks for the info!
